.TH corewatcher 8 "Aug 6, 2010"
.SH NAME
corewatcher - a program to collect backtrace data
.SH SYNOPSIS
.B corewatcher
.SH DESCRIPTION
This manual page documents briefly the
.B corewatcher
command.
.PP
\fBcorewatcher\fP is a program that collects user space program crash
information and then submits signature information and backtrace data
to a central website for for statistical analysis and presentation to
distribution developers.
.br
.SH OPTIONS
.LP

.TP
\fB\-d | \-\-debug\fR
Enable debug mode
.TP
\fB\-f | \-\-file\fR
Submit specific trace file
.TP
\fB\-n | \-\-nodaemon\fR
Do not daemonize
.TP
\fB\-a | \-\-always\fR
Send all crash data irregardless of other settings
.TP
\fB\-t | \-\-test\fR
Don't send anything, process 1 crash core file only, then exit
.TP
\fB\-h | \-\-help\fR
Display a brief option description
.SH AUTHOR
corewatcher was written by Arjan van de Ven <arjan@linux.intel.com>,
and Kaitlin Rupert <kaitlin.rupert@intel.com> and Auke Kok
<auke-jan.h.kok@intel.com>
.PP
