#!/bin/bash
shopt -s compat31

echo -n "Crash detected from following command: "

while read line
do
    if [[ $line =~ 'cmdline: (.*)' ]]; then
	echo ${BASH_REMATCH[0]}
    fi
done < $1

echo ""
echo "Backtrace"
while read line
do
    if [[ $line =~ 'backtrace:' ]]; then
	read line
	read line
	read line
    else
	continue
    fi

    while read line
    do
	if [[ $line =~ 'maps:' ]]; then
	    break
	fi
	echo $line
    done
done < $1

echo ""
echo "This information can be found in the file $1"
echo ""
echo "You can either restart or press Control+Alt+F1 to go back to your (possibly unstable) desktop."

curl -F "crash=`cat $1`" http://crashdb02.jf.intel.com/submit_crash/

#read -p "Submit crash? (Y/n): " -r -s -e -n 1 input

# if [ "$input" == 'n' -o "$input" == 'N' ]; then
#     echo "Done."
#     exit
# fi

# echo "Submitting..."
# echo "Done."

